### ISSUE TITLE
Do you have any plans to release Checkpoints?

### ISSUE THREAD

**Issue by hongliang-wei** [prateeky2806/ties-merging#1]
Thank you for your excellent work. Do you have any plans to release Checkpoints?

**Comment by RaptorMai** [comment]
Same question here! Thanks for sharing the code!

**Comment by TingchenFu** [comment]
Also looking forward to the checkpoint.

**Comment by prateeky2806** [comment]
Hi, we plan to release the checkpoint but it might take some time for that. However, it is not that hard to train the ia3 checkpoints you can use the latest version of the [huggingface peft](https://github.com/huggingface/peft) library which has ia3 built in. The training should be pretty fast depending on the dataset and the model size. However, for the vision experiments we used the checkpoints provided by the [task-arithmetic](https://github.com/mlfoundations/task_vectors) paper. These can be used for the vision experiments. 

I will post on this issue once I get back to school and I am able to release the checkpoints we used for NLP experiments.

**Comment by prateeky2806** [comment]
I have released the IA3 checkpoints. They can be found in the Readme!
