### ISSUE TITLE
Result conflicts with that in Editing Models with Task Arithmetic

### ISSUE THREAD

**Issue by cll-mtk** [prateeky2806/ties-merging#2]
Hi, 
In your paper, Fig. 5 indicates the average performance decreases when the number of merged tasks increases.
This is different from Fig. 3 in Editing Models with Task Arithmetic. How to explain this phenomenon.

**Comment by prateeky2806** [comment]
Hi @cll-mtk, Thanks for your question!

I would suggest that you look at Appendix D4 and Figure 16 from the [Editing Models with Task Arithmetic](https://arxiv.org/pdf/2212.04089.pdf). The results are consistent, however, they are presented in a more cryptic way in the Task Arithmetic paper.

Let me know if this does not answer your question, feel free to reopen the issue. 

Thanks,
Prateek
