### ISSUE TITLE
Questions about setup

### ISSUE THREAD

**Issue by SangRyul** [prateeky2806/ties-merging#4]
Hello, Thanks for your great work

I just wondered that the sentence in your setup README.md

4. Set the path to where finetuned models are stored in utils/merge_utils.py

Do you mean we have to do full fine-tune with each dataset like rte or story cloze dataset and use them?

I read the previous issue that you will release the checkpoint and I wonder the specific date.

Thank you very much for work and effort again.

**Comment by prateeky2806** [comment]
Hi @SangRyul, In the utils/merge_utils you would need to provide the path to the models that you want to merge, so it could either be full finetunes of a model or it could be a PEFT checkpoint. 

I plan to release the checkpoints once the paper is accepted at some venue. However, if you do not want to finetune a model on tasks you want to merge, then you can just use the checkpoints from HF hub. I have added a [minimal example](https://github.com/prateeky2806/ties-merging/blob/main/src/ties_minimal.ipynb) to perform TIES-Merging in a notebook, you can follow that. You would need your own setup to evaluate the merged checkpoint. 

Thanks,
Prateek
